/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas.layout;

import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author jkg
 */
public class PopFrame extends javax.swing.JFrame {

    
    private JPanel view;
    
    /**
     * Creates new form PopFrame
     */
    public PopFrame(JPanel view) {
        initComponents();
        this.view=view;
        this.setContentPane(view);
        this.setAlwaysOnTop(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setPreferredSize(new Dimension(view.getWidth(),view.getHeight()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
