/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas.facility;

import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.beans.PropertyChangeEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import mvc.Application;
import pas.exception.NoEntityManagerException;
import pas.layout.MainFrame;
import pas.layout.panel.iterate.FacilityListSearchResults;
import pas.main.MainController;
import pas.models.ActiveFacility;
import pas.models.SessionManager;
import pas.models.db.Faciliteit;
import session.NoSessionManagerException;

/**
 *
 * @author Bob
 */
public class Facility extends mvc.view.AbstractView {

    private FacilityController facilitycontroller;

    /**
     * Creates new form Facility
     */
    public Facility(FacilityController facilitycontroller) {
        this.facilitycontroller = facilitycontroller;
        initComponents();
        
        refreshTable();
    }

    @Override
    public FacilityController getController() {
        return this.facilitycontroller;
    }

    
    
    
    
    
    
    
    
    
    private SessionManager getSessionManager() {
        try {
            return (SessionManager) Application.getInstance().getSessionManager();
        } catch (NoSessionManagerException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    /*
     * Returns the database entity manager
     * 
     * @return EntityManager
     */
    private EntityManager getEntityManager() {
        try {
            return this.getSessionManager().getEntityManager();
        } catch (NoEntityManagerException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    
    
    
    
    
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        System.out.println("Test");
        switch (evt.getPropertyName()) {
            case ActiveFacility.FACILITEIT:
                this.setFaciliteit((Faciliteit) evt.getNewValue());
                break;
        }
    }

    
    
    
    
    
    
    public void setFacilityList(List<Faciliteit> facilityList) {
        System.out.println("TEST");
        pnlFacilitySearchResults.removeAll();
        FacilityListSearchResults.resetCounter();
        if (facilityList.size() > 0) {
            pnlFacilitySearchResults.setLayout(new GridLayout(facilityList.size(), 0));
            pnlFacilitySearchResults.repaint();
            GridBagConstraints gbc = new GridBagConstraints();
            for (Faciliteit facility : facilityList) {
                pnlFacilitySearchResults.add(
                        new FacilityListSearchResults(facility, this), gbc);
            }
        }

        pnlFacilitySearchResults.revalidate();
        pnlFacilitySearchResults.repaint();
    }

    
    
    
    
    public void refreshTable() {
        Query query = getEntityManager().createNamedQuery("Faciliteit.findAll");
        this.setFacilityList(query.getResultList());
    }
    
    
    
    
    
    

    public void updateFaciliteit() {
        String sql = "UPDATE Faciliteit SET name='" + this.txtSearchFaciliteit.getText() + "', "
                + "WHERE id='" + Integer.parseInt(this.txtSearchID.getText()) + "' ";

        try {
            if (!getEntityManager().getTransaction().isActive()) {
                getEntityManager().getTransaction().begin();
            }
            if (getEntityManager().getTransaction().isActive()) {
                System.out.println("Verbinding is actief");
            } else {
                System.out.println("Verbinding is niet actief");
            }

            Query query = getEntityManager().createQuery(sql);
            query.executeUpdate();
            getEntityManager().getTransaction().commit();
            this.refreshTable();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    
    
    
    
    
    
    public void setFaciliteit(Faciliteit faciliteit) {
        txtFaciliteitNaam.setText(faciliteit.getOmschrijving());
        txtFaciliteitKosten.setText(faciliteit.getKosten().toString());
        txtFaciliteitSoort.setText(faciliteit.getSoort());
        txtFaciliteitLocatie.setText(faciliteit.getVestigingid().toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnFacilityWijzigen = new javax.swing.JButton();
        btnFacilityOpslaan = new javax.swing.JButton();
        btnOverzichtReservering = new javax.swing.JButton();
        btnNieuweFaciliteit = new javax.swing.JButton();
        btnFacilityHoofdscherm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBeschrijving1 = new javax.swing.JTextArea();
        jLabel50 = new javax.swing.JLabel();
        txtFaciliteitNaam = new javax.swing.JTextField();
        txtFaciliteitSoort = new javax.swing.JTextField();
        txtFaciliteitKosten = new javax.swing.JTextField();
        txtFaciliteitLocatie = new javax.swing.JTextField();
        txtFaciliteitCapaciteit = new javax.swing.JTextField();
        txtFaciliteitCapaciteit1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        pnlFacilitySearchResults = new javax.swing.JPanel();
        txtSearchFaciliteit = new javax.swing.JTextField();
        txtSearchID = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setOpaque(false);

        jPanel2.setOpaque(false);

        jPanel7.setOpaque(false);

        btnFacilityWijzigen.setBackground(new java.awt.Color(155, 9, 46));
        btnFacilityWijzigen.setForeground(new java.awt.Color(255, 255, 255));
        btnFacilityWijzigen.setText("Wijzigen");
        btnFacilityWijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilityWijzigenActionPerformed(evt);
            }
        });

        btnFacilityOpslaan.setBackground(new java.awt.Color(155, 9, 46));
        btnFacilityOpslaan.setForeground(new java.awt.Color(255, 255, 255));
        btnFacilityOpslaan.setText("Opslaan");
        btnFacilityOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilityOpslaanActionPerformed(evt);
            }
        });

        btnOverzichtReservering.setBackground(new java.awt.Color(155, 9, 46));
        btnOverzichtReservering.setForeground(new java.awt.Color(255, 255, 255));
        btnOverzichtReservering.setText("Overzicht Reserveringen");
        btnOverzichtReservering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverzichtReserveringActionPerformed(evt);
            }
        });

        btnNieuweFaciliteit.setBackground(new java.awt.Color(155, 9, 46));
        btnNieuweFaciliteit.setForeground(new java.awt.Color(255, 255, 255));
        btnNieuweFaciliteit.setText("Nieuwe Faciliteit");
        btnNieuweFaciliteit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNieuweFaciliteitActionPerformed(evt);
            }
        });

        btnFacilityHoofdscherm.setBackground(new java.awt.Color(155, 9, 46));
        btnFacilityHoofdscherm.setForeground(new java.awt.Color(255, 255, 255));
        btnFacilityHoofdscherm.setText("Naar Hoofdmenu");
        btnFacilityHoofdscherm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilityHoofdschermActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFacilityWijzigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFacilityOpslaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOverzichtReservering, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(btnNieuweFaciliteit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFacilityHoofdscherm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnFacilityHoofdscherm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNieuweFaciliteit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOverzichtReservering)
                .addGap(13, 13, 13)
                .addComponent(btnFacilityWijzigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFacilityOpslaan)
                .addGap(52, 52, 52))
        );

        jPanel1.setOpaque(false);

        lblTitle1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(98, 98, 152));
        lblTitle1.setText("Faciliteit gegevens");

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algemeen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), java.awt.Color.darkGray)); // NOI18N
        jPanel23.setOpaque(false);

        jLabel45.setText("Kosten");

        jLabel46.setText("Naam");

        jLabel47.setText("Soort");

        jLabel48.setText("Locatie");

        jLabel49.setText("Beschrijving");

        txtBeschrijving1.setColumns(20);
        txtBeschrijving1.setRows(5);
        jScrollPane4.setViewportView(txtBeschrijving1);

        jLabel50.setText("Capaciteit");

        txtFaciliteitNaam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaciliteitNaamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel46))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(txtFaciliteitNaam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                                .addComponent(jLabel50)
                                .addGap(18, 18, 18)
                                .addComponent(txtFaciliteitCapaciteit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(txtFaciliteitSoort, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFaciliteitCapaciteit1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel45))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFaciliteitKosten, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFaciliteitLocatie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel49))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(txtFaciliteitNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(txtFaciliteitSoort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFaciliteitCapaciteit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txtFaciliteitKosten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(txtFaciliteitLocatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel50)
                    .addComponent(txtFaciliteitCapaciteit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(98, 98, 152));
        jLabel3.setText("Faciliteiten Beheren");

        jPanel4.setOpaque(false);

        jLabel1.setText("Faciliteit");

        jLabel2.setText("ID");

        lblTitle2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(98, 98, 152));
        lblTitle2.setText("Faciliteiten");

        javax.swing.GroupLayout pnlFacilitySearchResultsLayout = new javax.swing.GroupLayout(pnlFacilitySearchResults);
        pnlFacilitySearchResults.setLayout(pnlFacilitySearchResultsLayout);
        pnlFacilitySearchResultsLayout.setHorizontalGroup(
            pnlFacilitySearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlFacilitySearchResultsLayout.setVerticalGroup(
            pnlFacilitySearchResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        txtSearchFaciliteit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFaciliteitActionPerformed(evt);
            }
        });
        txtSearchFaciliteit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchFaciliteitKeyReleased(evt);
            }
        });

        txtSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchIDActionPerformed(evt);
            }
        });
        txtSearchID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTitle2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlFacilitySearchResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchFaciliteit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtSearchFaciliteit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pnlFacilitySearchResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacilityWijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilityWijzigenActionPerformed
        // TO Do
    }//GEN-LAST:event_btnFacilityWijzigenActionPerformed

    private void btnFacilityOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilityOpslaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacilityOpslaanActionPerformed

    private void btnOverzichtReserveringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverzichtReserveringActionPerformed
        new FacilityController().reservationChange();                // TODO add your handling code here:
    }//GEN-LAST:event_btnOverzichtReserveringActionPerformed

    private void btnNieuweFaciliteitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNieuweFaciliteitActionPerformed
        new FacilityController().addFacilityAction();        // TODO add your handling code here:
    }//GEN-LAST:event_btnNieuweFaciliteitActionPerformed

    private void btnFacilityHoofdschermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilityHoofdschermActionPerformed
        new MainController().mainAction();                // TODO add your handling code here:
    }//GEN-LAST:event_btnFacilityHoofdschermActionPerformed

    private void txtNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaamActionPerformed

    private void txtFaciliteitNaamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaciliteitNaamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaciliteitNaamActionPerformed

    private void txtSearchFaciliteitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFaciliteitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFaciliteitActionPerformed

    private void txtSearchFaciliteitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchFaciliteitKeyReleased
        Query query;
        if (txtSearchFaciliteit.getText().equals("")) {
            query = this.getEntityManager().createNamedQuery("Faciliteit.findAll");
        } else {
            query = this.getEntityManager()
                    .createNamedQuery("Faciliteit.findByOmschrijving")
                    .setParameter("omschrijving", "%" + txtSearchFaciliteit.getText() + "%");
        }

        this.setFacilityList(query.getResultList());        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchFaciliteitKeyReleased

    private void txtSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchIDActionPerformed

    private void txtSearchIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchIDKeyReleased
        Query query;
        if (txtSearchID.getText().equals("")) {
            query = this.getEntityManager().createNamedQuery("Faciliteit.findAll");
        } else {
            int test = Integer.parseInt(txtSearchID.getText());
            
            query = this.getEntityManager()
                    .createNamedQuery("Faciliteit.findById")
                    .setParameter("id", test);
        }

        this.setFacilityList(query.getResultList());        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchIDKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacilityHoofdscherm;
    private javax.swing.JButton btnFacilityOpslaan;
    private javax.swing.JButton btnFacilityWijzigen;
    private javax.swing.JButton btnNieuweFaciliteit;
    private javax.swing.JButton btnOverzichtReservering;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pnlFacilitySearchResults;
    private javax.swing.JTextArea txtBeschrijving1;
    private javax.swing.JTextField txtFaciliteitCapaciteit;
    private javax.swing.JTextField txtFaciliteitCapaciteit1;
    private javax.swing.JTextField txtFaciliteitKosten;
    private javax.swing.JTextField txtFaciliteitLocatie;
    private javax.swing.JTextField txtFaciliteitNaam;
    private javax.swing.JTextField txtFaciliteitSoort;
    private javax.swing.JTextField txtSearchFaciliteit;
    private javax.swing.JTextField txtSearchID;
    // End of variables declaration//GEN-END:variables
}
