/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas.course;

import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import java.util.List;
import pas.layout.form.ComboListItem;
import pas.models.ActiveMember;
import pas.models.Format;
import pas.models.db.Cursus;
import pas.models.db.Vestiging;
import pas.models.role.Member;

/**
 *
 * @author Ufuk Çelebi
 */
public class NewScheduleOrder extends mvc.view.AbstractView {

    private CourseController coursecontroller;
    private List<Cursus> courses = new ArrayList();
    private List<Vestiging> vestigingen;

    /**
     * Creates new form NewScheduleOrder
     *
     * @param NewScheduleOrder controller
     * @param Member active member
     * @param List<Cursus>
     */
    public NewScheduleOrder(CourseController coursecontroller) {
        initComponents();
        this.coursecontroller = coursecontroller;
        this.vestigingen = vestigingen;

        this.setVestigingen();
        this.setMember(member);

        ddlCourseOverview.setEnabled(false);
    }

    @Override
    public CourseController getController() {
        return this.coursecontroller;
    }

    @Override
    public void propertyChange(PropertyChangeEvent change) {
        switch (evt.getPropertyName()) {
            case ActiveMember.MEMBER:
                this.setMember((Member) evt.getNewValue());
                break;
        }
    }

    /*
     * Class helper to set member data
     * 
     * @param Member member
     * @return void
     */
    private void setMember(Member member) {

        txtMemberFirstName.setText(member.getFirstName());
        txtMemberLastName.setText(member.getLastName());
        txtMemberSuffix.setText(member.getSuffix());
        txtMemberBirthday.setText(Format.toShortDateString(member.getDateOfBrith()));
    }

    /*
     * Fill the course table and dropdown
     * 
     * @return void
     */
    private void setCourse() {
        ddlCourseOverview.removeAllItems();
        ddlCourseOverview.addItem(new ComboListItem("Selecteer cursus"));

        if (!this.course.isEmpty()) {
            for (Cursus course : course) {
                ddlCourseOverview.addItem(
                        new ComboListItem(
                        course.getOmschrijving(),
                        course));
            }

            ddlCourseOverview.setEnabled(true);
        } else {
            ddlCourseOverview.setEnabled(false);
        }

        ddlCourseOverview.repaint();
    }

    /*
     * Fill the location table and dropdown
     * 
     * @return void
     */
    private void setVestigingen() {
        ddlLocationOverview.addItem(new ComboListItem("Selecteer vestiging"));
        for (Vestiging vestinging : this.vestigingen) {
            ddlLocationOverview.addItem(
                    new ComboListItem(
                    vestinging.getNaam(),
                    vestinging));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNewScheduleOrder = new javax.swing.JPanel();
        lblNewScheduleOrder = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnGoBack = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        pnlNewScheduleOrderData = new javax.swing.JPanel();
        pnlOrderData = new javax.swing.JPanel();
        txtOrderID = new javax.swing.JTextField();
        lblOrderID = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        pnlOrderedSchedules = new javax.swing.JPanel();
        pnlOrderedSchedulesList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        btnAddSchedule = new javax.swing.JButton();
        btnDeleteSchedule = new javax.swing.JButton();
        pnlMemberData = new javax.swing.JPanel();
        lblMemberID = new javax.swing.JLabel();
        txtMemberID = new javax.swing.JTextField();
        lblMemberFirstName = new javax.swing.JLabel();
        txtMemberFirstName = new javax.swing.JTextField();
        lblMemberSuffix = new javax.swing.JLabel();
        txtMemberSuffix = new javax.swing.JTextField();
        lblMemberLastName = new javax.swing.JLabel();
        txtMemberLastName = new javax.swing.JTextField();
        lblMemberBirthday = new javax.swing.JLabel();
        txtMemberBirthday = new javax.swing.JTextField();
        lblMemberGender = new javax.swing.JLabel();
        txtMemberGender = new javax.swing.JTextField();
        lblMemberCredit = new javax.swing.JLabel();
        txtMemberCredit = new javax.swing.JTextField();
        lblMemberLatePayment = new javax.swing.JLabel();
        txtMemberLatePayment = new javax.swing.JTextField();
        pnlScheduleOverview = new javax.swing.JPanel();
        lblCourseOverview = new javax.swing.JLabel();
        lblScheduleDateOverview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        ddlScheduleDateDay = new java.awt.Choice();
        ddlScheduleDateMonth = new java.awt.Choice();
        ddlScheduleDateYear = new java.awt.Choice();
        lblLocationOverview = new javax.swing.JLabel();
        ddlLocationOverview = new java.awt.Choice();

        setOpaque(false);

        pnlNewScheduleOrder.setOpaque(false);

        lblNewScheduleOrder.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblNewScheduleOrder.setText("Inschrijving");

        pnlButtons.setOpaque(false);

        btnGoBack.setBackground(new java.awt.Color(155, 9, 46));
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Ga Terug");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(155, 9, 46));
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("Afrekenen");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGoBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPayment)
                .addContainerGap())
        );

        pnlNewScheduleOrderData.setOpaque(false);

        pnlOrderData.setBorder(javax.swing.BorderFactory.createTitledBorder("Bestel gegevens"));
        pnlOrderData.setOpaque(false);

        lblOrderID.setText("Bestellingnummer");

        lblEmployeeID.setText("Medewerker nummer");

        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOrderDataLayout = new javax.swing.GroupLayout(pnlOrderData);
        pnlOrderData.setLayout(pnlOrderDataLayout);
        pnlOrderDataLayout.setHorizontalGroup(
            pnlOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployeeID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtOrderID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOrderDataLayout.setVerticalGroup(
            pnlOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlOrderedSchedules.setBorder(javax.swing.BorderFactory.createTitledBorder("Bestelde Inschrijvingen"));
        pnlOrderedSchedules.setOpaque(false);

        pnlOrderedSchedulesList.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 0, 102), new java.awt.Color(0, 0, 0)));
        pnlOrderedSchedulesList.setOpaque(false);

        jScrollPane2.setOpaque(false);

        jPanel8.setOpaque(false);

        btnAddSchedule.setBackground(new java.awt.Color(155, 9, 46));
        btnAddSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSchedule.setText("Toevoegen");

        btnDeleteSchedule.setBackground(new java.awt.Color(155, 9, 46));
        btnDeleteSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteSchedule.setText("Verwijder");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSchedule)
                    .addComponent(btnDeleteSchedule))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout pnlOrderedSchedulesListLayout = new javax.swing.GroupLayout(pnlOrderedSchedulesList);
        pnlOrderedSchedulesList.setLayout(pnlOrderedSchedulesListLayout);
        pnlOrderedSchedulesListLayout.setHorizontalGroup(
            pnlOrderedSchedulesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderedSchedulesListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderedSchedulesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOrderedSchedulesListLayout.setVerticalGroup(
            pnlOrderedSchedulesListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderedSchedulesListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlOrderedSchedulesLayout = new javax.swing.GroupLayout(pnlOrderedSchedules);
        pnlOrderedSchedules.setLayout(pnlOrderedSchedulesLayout);
        pnlOrderedSchedulesLayout.setHorizontalGroup(
            pnlOrderedSchedulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderedSchedulesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrderedSchedulesList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOrderedSchedulesLayout.setVerticalGroup(
            pnlOrderedSchedulesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderedSchedulesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrderedSchedulesList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMemberData.setBorder(javax.swing.BorderFactory.createTitledBorder("Lid gegevens"));
        pnlMemberData.setOpaque(false);

        lblMemberID.setText("Lidnummer");

        lblMemberFirstName.setText("Voornaam");

        lblMemberSuffix.setText("Tussenvoegsel");

        lblMemberLastName.setText("Achternaam");

        lblMemberBirthday.setText("Geboortedatum");

        lblMemberGender.setText("Geslacht");

        lblMemberCredit.setText("Krediet");

        lblMemberLatePayment.setText("Betalingsachterstand");

        javax.swing.GroupLayout pnlMemberDataLayout = new javax.swing.GroupLayout(pnlMemberData);
        pnlMemberData.setLayout(pnlMemberDataLayout);
        pnlMemberDataLayout.setHorizontalGroup(
            pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMemberFirstName)
                    .addComponent(lblMemberID)
                    .addComponent(lblMemberSuffix)
                    .addComponent(lblMemberLastName)
                    .addComponent(lblMemberBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMemberGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMemberCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMemberLatePayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMemberID, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtMemberFirstName)
                    .addComponent(txtMemberSuffix)
                    .addComponent(txtMemberLastName)
                    .addComponent(txtMemberBirthday)
                    .addComponent(txtMemberGender)
                    .addComponent(txtMemberCredit)
                    .addComponent(txtMemberLatePayment))
                .addContainerGap())
        );
        pnlMemberDataLayout.setVerticalGroup(
            pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberID)
                    .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberFirstName)
                    .addComponent(txtMemberFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberSuffix)
                    .addComponent(txtMemberSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberLastName)
                    .addComponent(txtMemberLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberBirthday)
                    .addComponent(txtMemberBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberGender)
                    .addComponent(txtMemberGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberCredit)
                    .addComponent(txtMemberCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberLatePayment)
                    .addComponent(txtMemberLatePayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlScheduleOverview.setBorder(javax.swing.BorderFactory.createTitledBorder("Planning Overzichten"));
        pnlScheduleOverview.setOpaque(false);

        lblCourseOverview.setText("Cursus");

        lblScheduleDateOverview.setText("Datum");

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Planning nummer", "Cursusnummer", "Cursusnaam", "Datum", "Bezetting"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSchedule.setOpaque(false);
        jScrollPane1.setViewportView(tblSchedule);

        lblLocationOverview.setText("Locatie");

        javax.swing.GroupLayout pnlScheduleOverviewLayout = new javax.swing.GroupLayout(pnlScheduleOverview);
        pnlScheduleOverview.setLayout(pnlScheduleOverviewLayout);
        pnlScheduleOverviewLayout.setHorizontalGroup(
            pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                    .addGroup(pnlScheduleOverviewLayout.createSequentialGroup()
                        .addComponent(lblCourseOverview)
                        .addGap(145, 145, 145)
                        .addComponent(lblScheduleDateOverview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlScheduleDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlScheduleDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlScheduleDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLocationOverview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlLocationOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlScheduleOverviewLayout.setVerticalGroup(
            pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseOverview)
                        .addComponent(lblScheduleDateOverview))
                    .addComponent(ddlScheduleDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlScheduleDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblLocationOverview)
                        .addComponent(ddlScheduleDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ddlLocationOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlNewScheduleOrderDataLayout = new javax.swing.GroupLayout(pnlNewScheduleOrderData);
        pnlNewScheduleOrderData.setLayout(pnlNewScheduleOrderDataLayout);
        pnlNewScheduleOrderDataLayout.setHorizontalGroup(
            pnlNewScheduleOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewScheduleOrderDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewScheduleOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlScheduleOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlNewScheduleOrderDataLayout.createSequentialGroup()
                        .addGroup(pnlNewScheduleOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlOrderData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMemberData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlOrderedSchedules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNewScheduleOrderDataLayout.setVerticalGroup(
            pnlNewScheduleOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewScheduleOrderDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewScheduleOrderDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlNewScheduleOrderDataLayout.createSequentialGroup()
                        .addComponent(pnlOrderData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMemberData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlOrderedSchedules, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlScheduleOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout pnlNewScheduleOrderLayout = new javax.swing.GroupLayout(pnlNewScheduleOrder);
        pnlNewScheduleOrder.setLayout(pnlNewScheduleOrderLayout);
        pnlNewScheduleOrderLayout.setHorizontalGroup(
            pnlNewScheduleOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewScheduleOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNewScheduleOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNewScheduleOrderLayout.createSequentialGroup()
                        .addComponent(lblNewScheduleOrder)
                        .addContainerGap())
                    .addGroup(pnlNewScheduleOrderLayout.createSequentialGroup()
                        .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlNewScheduleOrderData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlNewScheduleOrderLayout.setVerticalGroup(
            pnlNewScheduleOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNewScheduleOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNewScheduleOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlNewScheduleOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlNewScheduleOrderData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(pnlNewScheduleOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlNewScheduleOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        coursecontroller.NewScheduleOrderAction();        // Deze button opent de view NewPlanningOrder
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        coursecontroller.PaymentScheduleAction();        // Deze button opent de view NewPlanningOrder
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        coursecontroller.ScheduleCourseAction();        // Deze button opent de view CourseMain
    }//GEN-LAST:event_btnGoBackActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSchedule;
    private javax.swing.JButton btnDeleteSchedule;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnPayment;
    private java.awt.Choice ddlLocationOverview;
    private java.awt.Choice ddlScheduleDateDay;
    private java.awt.Choice ddlScheduleDateMonth;
    private java.awt.Choice ddlScheduleDateYear;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseOverview;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblLocationOverview;
    private javax.swing.JLabel lblMemberBirthday;
    private javax.swing.JLabel lblMemberCredit;
    private javax.swing.JLabel lblMemberFirstName;
    private javax.swing.JLabel lblMemberGender;
    private javax.swing.JLabel lblMemberID;
    private javax.swing.JLabel lblMemberLastName;
    private javax.swing.JLabel lblMemberLatePayment;
    private javax.swing.JLabel lblMemberSuffix;
    private javax.swing.JLabel lblNewScheduleOrder;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblScheduleDateOverview;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlMemberData;
    private javax.swing.JPanel pnlNewScheduleOrder;
    private javax.swing.JPanel pnlNewScheduleOrderData;
    private javax.swing.JPanel pnlOrderData;
    private javax.swing.JPanel pnlOrderedSchedules;
    private javax.swing.JPanel pnlOrderedSchedulesList;
    private javax.swing.JPanel pnlScheduleOverview;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtMemberBirthday;
    private javax.swing.JTextField txtMemberCredit;
    private javax.swing.JTextField txtMemberFirstName;
    private javax.swing.JTextField txtMemberGender;
    private javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtMemberLastName;
    private javax.swing.JTextField txtMemberLatePayment;
    private javax.swing.JTextField txtMemberSuffix;
    private javax.swing.JTextField txtOrderID;
    // End of variables declaration//GEN-END:variables
}
