/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas.course;

import java.beans.PropertyChangeEvent;

/**
 *
 * @author Ufuk Çelebi
 */
public class ScheduleCourse extends mvc.view.AbstractView {

    private CourseController coursecontroller;
    /**
     * Creates new form ScheduleCourse
     */
    public ScheduleCourse(CourseController coursecontroller) {
        this.coursecontroller=coursecontroller;
        initComponents();
    }
    
    public CourseController getController(){
    return this.coursecontroller;
    }
    
    public void propertyChange(PropertyChangeEvent change){
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlScheduleManagement = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnChange = new javax.swing.JButton();
        btnNewSchedule = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNewScheduleOrder = new javax.swing.JButton();
        btnGoBack = new javax.swing.JButton();
        pnlScheduleOverview = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        lblOverviewScheduleID = new javax.swing.JLabel();
        txtOverviewScheduleID = new java.awt.TextField();
        lblOverviewCourseID = new javax.swing.JLabel();
        txtOverviewCourseID = new java.awt.TextField();
        lblOverviewCourseName = new javax.swing.JLabel();
        txtOverviewCourseName = new java.awt.TextField();
        lblOverviewScheduleDate = new javax.swing.JLabel();
        ddlOverviewScheduleDay = new java.awt.Choice();
        ddlOverviewScheduleMonth = new java.awt.Choice();
        ddlOverviewScheduleYear = new java.awt.Choice();
        pnlScheduleData = new javax.swing.JPanel();
        pnlScheduleGeneral = new javax.swing.JPanel();
        lblScheduleID = new javax.swing.JLabel();
        txtScheduleID = new javax.swing.JTextField();
        lblScheduleDate = new javax.swing.JLabel();
        ddlScheduleDay = new java.awt.Choice();
        ddlScheduleMonth = new java.awt.Choice();
        ddlScheduleYear = new java.awt.Choice();
        pnlLocationData = new javax.swing.JPanel();
        lblLocationID = new javax.swing.JLabel();
        txtLocationID = new javax.swing.JTextField();
        lblLocationName = new javax.swing.JLabel();
        txtLocationName = new javax.swing.JTextField();
        lblLocationStreetName = new javax.swing.JLabel();
        txtLocationStreetName = new javax.swing.JTextField();
        lblLocationHouseNumber = new javax.swing.JLabel();
        txtLocationHouseNumber = new javax.swing.JTextField();
        lblLocationSuffix = new javax.swing.JLabel();
        txtLocationSuffix = new javax.swing.JTextField();
        lblLocationZipCode = new javax.swing.JLabel();
        txtLocationZipCode = new javax.swing.JTextField();
        lblLocationCity = new javax.swing.JLabel();
        txtLocationCity = new javax.swing.JTextField();
        lblLocationTelNumber = new javax.swing.JLabel();
        txtLocationTelNumber = new javax.swing.JTextField();
        lblLocationEmail = new javax.swing.JLabel();
        txtLocationEmail = new javax.swing.JTextField();
        pnlCourseData = new javax.swing.JPanel();
        lblCourseID = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        lblCoursePrice = new javax.swing.JLabel();
        txtCoursePrice = new javax.swing.JTextField();
        lblCourseActivity = new javax.swing.JLabel();
        txtCourseActivity = new javax.swing.JTextField();
        lblCourseCapacity = new javax.swing.JLabel();
        txtCourseCapacity = new javax.swing.JTextField();
        lblCourseMinimum = new javax.swing.JLabel();
        txtCourseMinimum = new javax.swing.JTextField();
        lblCourseDuration = new javax.swing.JLabel();
        txtCourseDuration = new javax.swing.JTextField();
        lblCourseDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCourseDescription = new javax.swing.JTextArea();
        pnlEmployeeData = new javax.swing.JPanel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        lblEmployeeFirstName = new javax.swing.JLabel();
        txtEmployeeFirstName = new javax.swing.JTextField();
        lblEmployeeSuffix = new javax.swing.JLabel();
        txtEmployeeSuffix = new javax.swing.JTextField();
        lblEmployeeLastName = new javax.swing.JLabel();
        txtEmployeeLastName = new javax.swing.JTextField();
        lblEmployeeGender = new javax.swing.JLabel();
        txtEmployeeGender = new javax.swing.JTextField();
        lblEmployeeTelNumber = new javax.swing.JLabel();
        txtEmployeeTelNumber = new javax.swing.JTextField();
        lblEmployeeEmail = new javax.swing.JLabel();
        txtEmployeeEmail = new javax.swing.JTextField();

        setOpaque(false);

        pnlScheduleManagement.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setText("Planning Beheer");
        jLabel1.setPreferredSize(new java.awt.Dimension(129, 24));

        jPanel2.setOpaque(false);

        btnChange.setBackground(new java.awt.Color(155, 9, 46));
        btnChange.setForeground(new java.awt.Color(255, 255, 255));
        btnChange.setText("Wijzigen");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnNewSchedule.setBackground(new java.awt.Color(155, 9, 46));
        btnNewSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnNewSchedule.setText("Nieuw Planning");
        btnNewSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewScheduleActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(155, 9, 46));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Opslaan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(155, 9, 46));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Verwijderen");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNewScheduleOrder.setBackground(new java.awt.Color(155, 9, 46));
        btnNewScheduleOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnNewScheduleOrder.setText("Inschrijven");
        btnNewScheduleOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewScheduleOrderActionPerformed(evt);
            }
        });

        btnGoBack.setBackground(new java.awt.Color(155, 9, 46));
        btnGoBack.setForeground(new java.awt.Color(255, 255, 255));
        btnGoBack.setText("Ga Terug");
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(btnNewScheduleOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewScheduleOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoBack)
                .addContainerGap())
        );

        pnlScheduleOverview.setBorder(javax.swing.BorderFactory.createTitledBorder("Planning overzicht"));
        pnlScheduleOverview.setOpaque(false);

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Planningnummer", "Cursusnummer", "Cursusnaam", "Datum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSchedule);

        lblOverviewScheduleID.setText("Planningnummer");

        lblOverviewCourseID.setText("Cursusnummer");

        lblOverviewCourseName.setText("Cursusnaam");

        lblOverviewScheduleDate.setText("Datum");

        javax.swing.GroupLayout pnlScheduleOverviewLayout = new javax.swing.GroupLayout(pnlScheduleOverview);
        pnlScheduleOverview.setLayout(pnlScheduleOverviewLayout);
        pnlScheduleOverviewLayout.setHorizontalGroup(
            pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlScheduleOverviewLayout.createSequentialGroup()
                        .addComponent(lblOverviewScheduleID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOverviewScheduleID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOverviewCourseID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOverviewCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOverviewCourseName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOverviewCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOverviewScheduleDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlOverviewScheduleDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlOverviewScheduleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlOverviewScheduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlScheduleOverviewLayout.setVerticalGroup(
            pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleOverviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScheduleOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOverviewScheduleID)
                    .addComponent(txtOverviewScheduleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOverviewCourseID)
                    .addComponent(txtOverviewCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOverviewCourseName)
                    .addComponent(txtOverviewCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOverviewScheduleDate)
                    .addComponent(ddlOverviewScheduleDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlOverviewScheduleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlOverviewScheduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlScheduleData.setBorder(javax.swing.BorderFactory.createTitledBorder("Planning gegevens"));
        pnlScheduleData.setOpaque(false);

        pnlScheduleGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("Algemeen"));
        pnlScheduleGeneral.setOpaque(false);

        lblScheduleID.setText("Planningnummer");

        lblScheduleDate.setText("Datum");

        javax.swing.GroupLayout pnlScheduleGeneralLayout = new javax.swing.GroupLayout(pnlScheduleGeneral);
        pnlScheduleGeneral.setLayout(pnlScheduleGeneralLayout);
        pnlScheduleGeneralLayout.setHorizontalGroup(
            pnlScheduleGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlScheduleGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblScheduleID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblScheduleDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlScheduleGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlScheduleGeneralLayout.createSequentialGroup()
                        .addComponent(ddlScheduleDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlScheduleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ddlScheduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtScheduleID))
                .addContainerGap())
        );
        pnlScheduleGeneralLayout.setVerticalGroup(
            pnlScheduleGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScheduleGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScheduleID)
                    .addComponent(txtScheduleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlScheduleGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblScheduleDate)
                    .addComponent(ddlScheduleDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlScheduleMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddlScheduleYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlLocationData.setBorder(javax.swing.BorderFactory.createTitledBorder("Locatie gegevens"));
        pnlLocationData.setOpaque(false);

        lblLocationID.setText("Locatienummer");

        lblLocationName.setText("Naam");

        lblLocationStreetName.setText("Straatnaam");

        lblLocationHouseNumber.setText("Huisnummer");

        lblLocationSuffix.setText("Achtervoegsel");

        lblLocationZipCode.setText("Postcode");

        lblLocationCity.setText("Woonplaats");

        lblLocationTelNumber.setText("Telefoonnummer");

        lblLocationEmail.setText("Email");

        javax.swing.GroupLayout pnlLocationDataLayout = new javax.swing.GroupLayout(pnlLocationData);
        pnlLocationData.setLayout(pnlLocationDataLayout);
        pnlLocationDataLayout.setHorizontalGroup(
            pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocationDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationID, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationID, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationName))
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationStreetName))
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationHouseNumber))
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationSuffix))
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationZipCode))
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationCity, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationCity))
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationTelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationTelNumber))
                    .addGroup(pnlLocationDataLayout.createSequentialGroup()
                        .addComponent(lblLocationEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocationEmail)))
                .addContainerGap())
        );
        pnlLocationDataLayout.setVerticalGroup(
            pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocationDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationID)
                    .addComponent(txtLocationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationName)
                    .addComponent(txtLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationStreetName)
                    .addComponent(txtLocationStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationHouseNumber)
                    .addComponent(txtLocationHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationSuffix)
                    .addComponent(txtLocationSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationZipCode)
                    .addComponent(txtLocationZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationCity)
                    .addComponent(txtLocationCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationTelNumber)
                    .addComponent(txtLocationTelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLocationDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocationEmail)
                    .addComponent(txtLocationEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlCourseData.setBorder(javax.swing.BorderFactory.createTitledBorder("Cursus gegevens"));
        pnlCourseData.setOpaque(false);

        lblCourseID.setText("Cursusnummer");

        lblCourseName.setText("Naam");

        lblCoursePrice.setText("Prijs");

        lblCourseActivity.setText("Activiteit");

        lblCourseCapacity.setText("Capaciteit");

        lblCourseMinimum.setText("Minimum");

        lblCourseDuration.setText("Duur");

        lblCourseDescription.setText("Omschrijving");

        txtCourseDescription.setColumns(20);
        txtCourseDescription.setRows(5);
        jScrollPane2.setViewportView(txtCourseDescription);

        javax.swing.GroupLayout pnlCourseDataLayout = new javax.swing.GroupLayout(pnlCourseData);
        pnlCourseData.setLayout(pnlCourseDataLayout);
        pnlCourseDataLayout.setHorizontalGroup(
            pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCourseDataLayout.createSequentialGroup()
                        .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCourseDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCourseMinimum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCourseCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCourseActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCoursePrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCourseID, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblCourseDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseID)
                            .addComponent(txtCourseName)
                            .addComponent(txtCoursePrice)
                            .addComponent(txtCourseActivity)
                            .addComponent(txtCourseCapacity)
                            .addComponent(txtCourseMinimum)
                            .addComponent(txtCourseDuration)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCourseDataLayout.setVerticalGroup(
            pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseID)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseName)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoursePrice)
                    .addComponent(txtCoursePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseActivity)
                    .addComponent(txtCourseActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseCapacity)
                    .addComponent(txtCourseCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseMinimum)
                    .addComponent(txtCourseMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCourseDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseDuration)
                    .addComponent(txtCourseDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCourseDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEmployeeData.setBorder(javax.swing.BorderFactory.createTitledBorder("Medewerker gegevens"));
        pnlEmployeeData.setOpaque(false);

        lblEmployeeID.setText("Medewerkernummer");

        lblEmployeeFirstName.setText("Voornaam");

        lblEmployeeSuffix.setText("Tussenvoegsel");

        lblEmployeeLastName.setText("Achternaam");

        lblEmployeeGender.setText("Geslacht");

        lblEmployeeTelNumber.setText("Telefoonnummer");

        lblEmployeeEmail.setText("Email");

        javax.swing.GroupLayout pnlEmployeeDataLayout = new javax.swing.GroupLayout(pnlEmployeeData);
        pnlEmployeeData.setLayout(pnlEmployeeDataLayout);
        pnlEmployeeDataLayout.setHorizontalGroup(
            pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblEmployeeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployeeTelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployeeGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployeeLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployeeSuffix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployeeFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmployeeID)
                    .addComponent(txtEmployeeFirstName)
                    .addComponent(txtEmployeeSuffix)
                    .addComponent(txtEmployeeLastName)
                    .addComponent(txtEmployeeGender)
                    .addComponent(txtEmployeeTelNumber)
                    .addComponent(txtEmployeeEmail))
                .addContainerGap())
        );
        pnlEmployeeDataLayout.setVerticalGroup(
            pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmployeeDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeFirstName)
                    .addComponent(txtEmployeeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeSuffix)
                    .addComponent(txtEmployeeSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeLastName)
                    .addComponent(txtEmployeeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeGender)
                    .addComponent(txtEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeTelNumber)
                    .addComponent(txtEmployeeTelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmployeeDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeEmail)
                    .addComponent(txtEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlScheduleDataLayout = new javax.swing.GroupLayout(pnlScheduleData);
        pnlScheduleData.setLayout(pnlScheduleDataLayout);
        pnlScheduleDataLayout.setHorizontalGroup(
            pnlScheduleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScheduleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlScheduleGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEmployeeData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCourseData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLocationData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlScheduleDataLayout.setVerticalGroup(
            pnlScheduleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScheduleDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlScheduleDataLayout.createSequentialGroup()
                        .addComponent(pnlScheduleGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEmployeeData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlCourseData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLocationData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlScheduleManagementLayout = new javax.swing.GroupLayout(pnlScheduleManagement);
        pnlScheduleManagement.setLayout(pnlScheduleManagementLayout);
        pnlScheduleManagementLayout.setHorizontalGroup(
            pnlScheduleManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScheduleManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlScheduleManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlScheduleData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlScheduleOverview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlScheduleManagementLayout.setVerticalGroup(
            pnlScheduleManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScheduleManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlScheduleManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlScheduleManagementLayout.createSequentialGroup()
                        .addComponent(pnlScheduleOverview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlScheduleData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(pnlScheduleManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlScheduleManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewScheduleActionPerformed
       coursecontroller.AddScheduleAction();        // Deze button opent de view AddPlanning
    }//GEN-LAST:event_btnNewScheduleActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        coursecontroller.ScheduleCourseAction();        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        coursecontroller.ScheduleCourseAction();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        coursecontroller.ScheduleCourseAction();        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        coursecontroller.CourseMainAction();        // Deze button opent de view CourseMain
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnNewScheduleOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewScheduleOrderActionPerformed
        coursecontroller.NewScheduleOrderAction();        // Deze button opent de view NewScheduleOrder
    }//GEN-LAST:event_btnNewScheduleOrderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnNewSchedule;
    private javax.swing.JButton btnNewScheduleOrder;
    private javax.swing.JButton btnSave;
    private java.awt.Choice ddlOverviewScheduleDay;
    private java.awt.Choice ddlOverviewScheduleMonth;
    private java.awt.Choice ddlOverviewScheduleYear;
    private java.awt.Choice ddlScheduleDay;
    private java.awt.Choice ddlScheduleMonth;
    private java.awt.Choice ddlScheduleYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCourseActivity;
    private javax.swing.JLabel lblCourseCapacity;
    private javax.swing.JLabel lblCourseDescription;
    private javax.swing.JLabel lblCourseDuration;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseMinimum;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCoursePrice;
    private javax.swing.JLabel lblEmployeeEmail;
    private javax.swing.JLabel lblEmployeeFirstName;
    private javax.swing.JLabel lblEmployeeGender;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeLastName;
    private javax.swing.JLabel lblEmployeeSuffix;
    private javax.swing.JLabel lblEmployeeTelNumber;
    private javax.swing.JLabel lblLocationCity;
    private javax.swing.JLabel lblLocationEmail;
    private javax.swing.JLabel lblLocationHouseNumber;
    private javax.swing.JLabel lblLocationID;
    private javax.swing.JLabel lblLocationName;
    private javax.swing.JLabel lblLocationStreetName;
    private javax.swing.JLabel lblLocationSuffix;
    private javax.swing.JLabel lblLocationTelNumber;
    private javax.swing.JLabel lblLocationZipCode;
    private javax.swing.JLabel lblOverviewCourseID;
    private javax.swing.JLabel lblOverviewCourseName;
    private javax.swing.JLabel lblOverviewScheduleDate;
    private javax.swing.JLabel lblOverviewScheduleID;
    private javax.swing.JLabel lblScheduleDate;
    private javax.swing.JLabel lblScheduleID;
    private javax.swing.JPanel pnlCourseData;
    private javax.swing.JPanel pnlEmployeeData;
    private javax.swing.JPanel pnlLocationData;
    private javax.swing.JPanel pnlScheduleData;
    private javax.swing.JPanel pnlScheduleGeneral;
    private javax.swing.JPanel pnlScheduleManagement;
    private javax.swing.JPanel pnlScheduleOverview;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtCourseActivity;
    private javax.swing.JTextField txtCourseCapacity;
    private javax.swing.JTextArea txtCourseDescription;
    private javax.swing.JTextField txtCourseDuration;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseMinimum;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCoursePrice;
    private javax.swing.JTextField txtEmployeeEmail;
    private javax.swing.JTextField txtEmployeeFirstName;
    private javax.swing.JTextField txtEmployeeGender;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeLastName;
    private javax.swing.JTextField txtEmployeeSuffix;
    private javax.swing.JTextField txtEmployeeTelNumber;
    private javax.swing.JTextField txtLocationCity;
    private javax.swing.JTextField txtLocationEmail;
    private javax.swing.JTextField txtLocationHouseNumber;
    private javax.swing.JTextField txtLocationID;
    private javax.swing.JTextField txtLocationName;
    private javax.swing.JTextField txtLocationStreetName;
    private javax.swing.JTextField txtLocationSuffix;
    private javax.swing.JTextField txtLocationTelNumber;
    private javax.swing.JTextField txtLocationZipCode;
    private java.awt.TextField txtOverviewCourseID;
    private java.awt.TextField txtOverviewCourseName;
    private java.awt.TextField txtOverviewScheduleID;
    private javax.swing.JTextField txtScheduleID;
    // End of variables declaration//GEN-END:variables
}
