/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pas.member;

import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import javax.swing.JFileChooser;
import pas.file.chooser.FileChooserAbstract;
import pas.file.chooser.FileChooserImage;
import pas.file.chooser.FileChooserInterface;

/**
 *
 * @author jkg
 */
public class MemberIndex extends mvc.view.AbstractView implements FileChooserInterface {

    private MemberController membercontroller;
    private FileChooserAbstract fileChooser;

    /**
     * Creates new form manageMember
     */
    public MemberIndex(MemberController controller) {
        initComponents();
        this.membercontroller = controller;
    }

    @Override
    public MemberController getController() {
        return this.membercontroller;
    }

    public FileChooserAbstract getFileChooser() {
        if (null == this.fileChooser) {
            this.fileChooser = new FileChooserImage(this);
        }

        return fileChooser;
    }

    public void setFileChooser(FileChooserAbstract fileChooser) {
        this.fileChooser = fileChooser;
    }

    /**
     * Called to push events from the file chooser to the calling view
     *
     * @param evt
     * @return void
     */
    @Override
    public void fileChooserActionPerformed(ActionEvent evt) {
        FileChooserAbstract chooser = this.getFileChooser();

        if (JFileChooser.APPROVE_SELECTION.equals(evt.getActionCommand())) {
            chooser.setVisible(false);
            chooser.dispose();
        } else if (JFileChooser.CANCEL_SELECTION.equals(evt.getActionCommand())) {
            chooser.setVisible(false);
            chooser.dispose();
        }
    }

    @Override
    public void propertyChange(PropertyChangeEvent change) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
