package pas.layout.panel.iterate;

import java.awt.Color;
import javax.swing.JPanel;
import pas.models.db.Member1;

/**
 *
 * @author Frank
 */
public class SidebarMemberSearchResult extends JPanel {

    // Counter
    private static int counter = 1;
    
    // Alternating background colors
    public static final Color COLOR_ODD = new Color(255, 255, 255);
    public static final Color COLOR_EVEN  = new Color(222, 222, 222);
    
    /**
     * Creates new form SidebarMemberSearchResult
     */
    public SidebarMemberSearchResult(Member1 member) {
        initComponents();
        lblMemberName.setText(member.getFirstname() + " " + member.getLastname());
        lblMemberId.setText(member.getId().toString());
        
        if (counter % 2 == 0) {
            setBackground(SidebarMemberSearchResult.COLOR_EVEN);
        } else {
            setBackground(SidebarMemberSearchResult.COLOR_ODD);
        }
        
        SidebarMemberSearchResult.counter ++;
    }
    
    /*
     * Reset the alternate counter
     * 
     * @return void
     */
    public static void resetCounter() {
        SidebarMemberSearchResult.counter = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMemberName = new javax.swing.JLabel();
        lblMemberId = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(246, 20));
        setMinimumSize(new java.awt.Dimension(246, 20));
        setPreferredSize(new java.awt.Dimension(246, 20));

        lblMemberName.setText("Member name");

        lblMemberId.setText("Member id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMemberName, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
            .addComponent(lblMemberId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMemberId;
    private javax.swing.JLabel lblMemberName;
    // End of variables declaration//GEN-END:variables
}
